name 'gemrc'
maintainer 'OptimisCorp., Inc.'
maintainer_email 'ops+cookbooks@optimiscorp.com'
license 'Apache 2.0'
description 'Library cookbook which manages a RubyGems configuration file.'
long_description 'Library cookbook which manages a RubyGems configuration file.'
version '1.2.0'
source_url 'https://github.com/optimis/chef-gemrc'
issues_url 'https://github.com/optimis/chef-gemrc/issues'

depends 'poise', '~> 2.2'
